#! /bin/bash

docker stop grafana-influxdb_con
docker rm grafana-influxdb_con

docker run -d -v /etc/localtime:/etc/localtime:ro -v /etc/graf-infl/influxdb/db:/var/easydeploy/share/db:rw -p 80:80 -p 8083:8083 -p 8084:8084 -p 8086:8086 --name graf-infl grafana_influxdb