#! /bin/bash

docker stop graf-infl
docker rm graf-infl

docker run -d -v /etc/localtime:/etc/localtime:ro -v /mnt/db:/mnt/db:rw -p 80:80 -p 8083:8083 -p 8084:8084 -p 8086:8086 --name graf-infl grafana_influxdb